language: php
php:
    - '5.6'

env:
    - SYMFONY_ENV=prod

before_install:
    - bin/console doc:database:create
    - bin/console doc:schema:update --force

install:
    - composer install --no-interaction --prefer-source

script: phpunit -c app/

