language: php
php:
    - '5.6'

env:
    - SYMFONY_ENV=prod

before_install:
      - mysql -e 'CREATE DATABASE symfony;'

install:
    - composer install --no-interaction --prefer-source

script: phpunit -c app/

